apiVersion: v1
kind: ServiceAccount
metadata:
  name: heimdall-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heimdall-role
rules:
  - apiGroups:
      - ""
      - flink.apache.org
    resources:
      - flinkdeployments
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heimdall-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: heimdall-role
subjects:
  - kind: ServiceAccount
    name: heimdall-service-account
