name: Release

on:
  issue_comment:
    types: [created]

jobs:
  release:
    runs-on: java-tools-latest
    if: ${{ github.event.issue.title == 'Actions Run' && startsWith(github.event.comment.body, '!actions run release') }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ingest Gitea secrets
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "prod"
          project-slug: "homelab-058-n"
          secret-path: "/gitea"
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Build, tag, and push image
        env:
          FULL_IMAGE_NAME: ${{ vars.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}
        run: |
          version=$(gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "Using version: $version"
          echo "heimdall_version=$version" >> "$GITHUB_ENV"
          gradle -x test build -i -Pversion=$version -Dquarkus.container-image.build=true -Dquarkus.container-image.image=$FULL_IMAGE_NAME:$version -Dquarkus.container-image.push=true
